theme: minima
title: Mohamed Rafick
description: Mechanical Engineer | Professional Portfolio

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/custom.css"
